### ISSUE TITLE
Create article on creating config files in R

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubAdmin#8]
Dependant on resolving Infectious-Disease-Modeling-Hubs/hubAdmin#7 & https://github.com/ropensci/jsonvalidate/issues/65

**Comment by nickreich** [comment]
Noting that this issue is a duplicate of [this one](https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/issues/100). So I will close this one in favor of the other. @micokoch does the discussion on the other issue resolve any lingering questions?

**Comment by micokoch** [comment]
I think the discussion on the other issue addresses most of my questions, and I'll take a stab at it on Wednesday.
